services:
  - type: web
    name: Be-Her-Best
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt && python Website/myproject/manage.py collectstatic --noinput"
    startCommand: "gunicorn myproject.wsgi"
    rootDir: Website/myproject
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        sync: false 