services:
  - type: web
    name: myproject
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi"
    rootDir: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myproject-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
databases:
  - name: myproject-db
    databaseName: myproject
    user: myproject
    plan: free 