# Generated by Django 5.1.7 on 2025-04-03 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googledrivefolder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videoprogress',
            options={},
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='_video_count',
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='membership_tier',
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='required_membership',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP'), ('diamond', 'Diamond')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='sync_interval',
            field=models.IntegerField(default=60, help_text='Sync interval in minutes. Minimum 15 minutes.'),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='googledrivefolder',
            name='auto_sync',
            field=models.BooleanField(default=True, help_text='Automatically sync videos from this folder'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='current_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.googledrivevideo'),
        ),
    ]
