# Generated by Django 5.1.7 on 2025-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_googledrivefolder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googledrivefolder',
            options={},
        ),
        migrations.AlterField(
            model_name='googledrivefolder',
            name='video_count',
            field=models.IntegerField(db_column='video_count', default=0),
        ),
        migrations.RenameField(
            model_name='googledrivefolder',
            old_name='video_count',
            new_name='_video_count',
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='required_membership',
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='sync_interval',
        ),
        migrations.RemoveField(
            model_name='googledrivefolder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='membership_tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('diamond', 'Diamond')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='googledrivefolder',
            name='auto_sync',
            field=models.BooleanField(default=False),
        ),
    ]
